schema_version: 1

context:
  version: "1.4.0"

package:
  name: pyrage-stubs
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyrage-stubs/pyrage_stubs-${{ version }}.tar.gz
  sha256: 9a44b0c1d2c169c67745ccb5790fcd1dd716941e9c4c4a66ecbd0862584766d9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - pyrage >=${{ version }},<2.0

tests:
  - python:
      imports:
        - pyrage
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - package_contents:
      strict: true
      site_packages:
        - pyrage/*.pyi
        - pyrage/py.typed
        - pyrage_stubs-${{ version }}.dist-info/*

about:
  summary: A PEP 561 stub package for pyrage's types
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/woodruffw/pyrage
  repository: https://github.com/woodruffw/pyrage/tree/main/pyrage-stubs

extra:
  recipe-maintainers:
    - pavelzw
